version: "3"
services:
  jenkins:
    image: registry.aliyuncs.com/hydsoft/ddc-jenkins-server:latest
    ports:
      - "8080:8080"
    networks:
      - jenkins-ci
  jenkins-slave:
    image: registry.aliyuncs.com/hydsoft/ddc-jenkins-slave:latest
    environment:
      - UCP_SERVERS=
      - UCP_USER=
      - UCP_PASSWORD=
      - NODE_NAME=agent
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_USER=
      - JENKINS_PASSWORD=
      - EXECUTORS=2
      - LABELS=slave
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.m2:/root/.m2
    depends_on:
      - jenkins
    networks:
      - jenkins-ci

networks:
  jenkins-ci:
    driver: overlay
