version: "3"
services:
  jenkins:
    image: registry.aliyuncs.com/hydsoft/ddc-jenkins-server:latest
    ports:
      - "8090:8080"
  jenkins-slave:
    image: registry.aliyuncs.com/hydsoft/ddc-jenkins-slave:latest
    environment:
      - UCP_SERVERS=10.0.0.4
      - UCP_USER=admin
      - UCP_PASSWORD=1qaz@WSX
      - NODE_NAME=agent
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_USER=
      - JENKINS_PASSWORD=
      - EXECUTORS=2
      - LABELS=slave
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins
